-- phpMyAdmin SQL Dump
-- version 4.9.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Jun 07, 2020 at 01:28 PM
-- Server version: 5.7.26
-- PHP Version: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `humansofbilkent`
--

-- --------------------------------------------------------

--
-- Table structure for table `story`
--

CREATE TABLE `story` (
  `id` int(11) NOT NULL,
  `content` varchar(10000) NOT NULL,
  `picture` varchar(80) NOT NULL,
  `tags` varchar(200) NOT NULL DEFAULT 'humansofbilkent',
  `views` int(11) NOT NULL DEFAULT '0',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `story`
--

INSERT INTO `story` (`id`, `content`, `picture`, `tags`, `views`, `created`) VALUES
(1, 'Hey Bilkentliler! Alot of you might be wondering what exactly this page is for. Well, this post is just to tell you whats coming up. Over the course of our time at Bilkent, we have met countless people, many of whom just become familiar faces on campus and nothing more. Each of these faces has breathtaking stories just waiting to be told, stories more interesting than many of us have ever heard. We are here to make sure these come forward, and that this small community of our followers relates to the 14000 stories the 14000 individuals of bilkent bring! ', 'img/story/humansofbilkent0.jpg', 'humansofbilkent misc uplift', 174, '2020-06-06 10:06:13'),
(2, '“We met at a mutual friend\'s birthday party. Even though it was our first encounter, things felt so comfortable around him. It didn\'t take any more than one casual conversation concerning our shared interest in under-appreciated films and a little bit of whiskey for us to realize how much we have in common. The cornerstone of this was love for the work of the Canadian director, Xavier Dolan. We have watched a multitude of Dolan\'s movies together and shared some great moments during those times. It\'s a remarkable feeling to have someone care for you enough to take a genuine interest in your likings. It\'s incredible how a director from Canada can connect two people from Bilkent.” ', 'img/story/humansofbilkent1.jpg', 'humansofbilkent person couple uplift maysfest', 226, '2020-06-06 10:06:14'),
(3, '“People are reserved around Bilkent, aren\'t they? This indifferent attitude in Bilkent\'s community became more apparent to me during my summer in Ohio, US. I worked at a winery, and a significant part of my day revolved around meeting people from various backgrounds. A common characteristic amongst most of these people was their ability to open up to a stranger. They share and encourage you to share. I felt that approaching a stranger and opening up a little was just a regular part of their day. \r\n\r\nDuring my stay in the US, I gradually realized how talking to and smiling at strangers might seem trivial yet make a huge difference in establishing a community without social awkwardness. That\'s the most important lesson that I brought back with me. \r\n\r\nI was not the type of person who used to randomly talk with others. I guess I smile more often now or say \'hi\' to a familiar stranger because that\'s the least I can to do to make a difference. Just today, I saw a girl standing in front of a mirror and realized that we\'ve been living in the same dorm for about a year now and have never talked. I confronted her with some small talk. Things felt strange for a couple of seconds at first; however, at least we are now not completely oblivious to each other. I think it makes me feel better and might even help others build up their confidence. \r\n\r\nI would love to live on a campus where smiling at strangers is not a burden. A place where people are more engaged with one another and a community where people can open up to strangers. Wouldn\'t it help reduce the stress that people experience at this university? \r\n\r\nMy advice to the people around here is, always be open to sharing something. It doesn\'t have to be personal!” ', 'img/story/humansofbilkent2.jpg', 'humansofbilkent person girl uplift social 8081', 146, '2020-06-06 14:14:23'),
(334, '“Before coming to Ankara I dreamt of double majoring in Computer Engineering with Economics. For me, life was sunshine and rainbows when I came to Bilkent. I didn’t realize that there was a calculus course which would be the breaking point for me. It wasn’t that I didn’t get the subject matter, but that it was so bland that It made me realize that I was going to encounter similar subjects if I was to remain in this department and how irrelevant these subjects were with what I want to pursue in my life.This, together with my strong interest in Computer Science and Economics, made me consider switching from CS to CTIS, that I never considered being an option before but after thorough research seemed a perfect match for me. I admit that my liking towards CTIS over CS might be subjective as it is more of what I desire to do. \r\n\r\nEnjoying every class in Bilkent is rare right? In CTIS, I am the guy who loves going to my classes.\r\n\r\nFor me, the first year in this department was all about the grades as I was trying to prove a point to myself. I got the highest possible GPA for two consecutive semesters and spent the entire summer practicing coding. \r\n\r\nHowever, last summer I went to Singapore for my internship and began to notice that the world does not work on letter grades. I realized this when I was around people with PHDs from Harvard and MIT who never showed any signs that they felt I was any lesser than them. They valued me on my skills and the work I produced instead of the As and Bs that I had in my transcript. \r\n\r\nI think this is how the real world works. The skills you acquire during your university life would always be valued above your academic credentials and would help you succeed in your professional life no matter what subject you majored in.”', 'img/story/humansofbilkent3.jpg', 'humansofbilkent hill boy uplift study', 3387, '2020-06-06 20:12:55'),
(335, '“They were saved off the street and honestly, I feel that they’re like my children. Each one of them holds a special place in my heart and makes life a bit more colorful. They understand me so well, whenever I’m depressed or upset, Değerli tries to console me in his way by licking my face. Whenever I’m sick, all of them stay with me in my bed to give me company. \r\n\r\nI don’t have any favorites, each of them is unique is so is their story; I love them all equally. Papatya is the most docile one. She walks with me every day and always finds her way towards me. She gets sad when I’m leaving home. So, does each of the rest. \r\n\r\nLoui was ill when he was a puppy. I was there for him then; we formed a special bond, and it’s still strong, since then he’s been there for me whenever things get tough. \r\n\r\nDeğerli loves being around people, he’s very playful. However, he has a strong sense of foresight. Whenever he sees someone with bad intentions approaching me, he warns me by barking at them. There have been times when he has figured out that a person would be bad for me in the long run, before I did! \r\n\r\nI don\'t often bring them to Bilkent. Just today, when I went to take two lectures, they kept on barking until I was back, for two straight hours! But I guess this just depicts how much they love me. \r\n\r\nSave a stray dogs off the street, you never know how much color they will bring to your life!”.', 'img/story/humansofbilkent4.jpg', 'humansofbilkent animal girl mayfest uplift', 3018, '2020-06-06 20:15:29'),
(336, '\"My life in Bilkent has been a rollercoaster ride, full of ups and downs, highs and lows, and it feels like I’ve seen most out of what this university has to offer. I enrolled in Bilkent as an MBG student, but within my very first year, I realized that this highly specific academic field that required hours of research and effort in labs was not for me. I wanted to study something that involved social interaction so I took a bold decision of changing my department to International Relations. \r\n\r\nIn my point of view, IR students are more aware of the politics and international affairs and are more open to engaging in constructive arguments about random issues than students from MBG who are more focused on academics and research. I know they are two different dimensions but I\'m happy I experienced the best of both. Of course, I only spent one year in the MBG department, so my opinion might sound cliched. Nevertheless, I’m glad that I switched my department. \r\n\r\nBefore coming to Bilkent, I was an exchange student in Germany and I met various people from around the world. I used to party often then, so I had the chance of seeing people genuinely enjoy their time at these events. But I feel people miss that here, they take everything as if it\'s a duty or a responsibility. Even at Mayfest, you would see people attending this event not because they want to but as a self-imposed obligation. Also, most students of Bilkent are reserved and prefer to remain in the same group throughout their university life. I just hope that we could break this monotonous cycle and genuinely enjoy college while it lasts!\"', 'img/story/humansofbilkent5.jpg', 'humansofbilkent girl fountain studies uplift study', 2549, '2020-06-06 20:18:07'),
(337, '\"I didn\'t know what to expect before leaving Belgium and coming to Turkey, which I think you would understand since it was a completely foreign place. However, only after 3 days here, I began to realize that a semester is not going to be enough in this magnificent country. \r\n\r\nI\'m amazed at how much I have been able to explore during my time here. I often find myself sitting at a table with more than 8 different nationalities juggling between the four different languages I am familiar with. At the end of the day, I’m sometimes confused about what language to think in; It’s an amazing experience!\r\n\r\nThere\'s something I need to mark off my bucket list though: visiting the eastern part of Turkey to explore the centuries-old heritage and customs that represent the true origins of Turkey and its cultural diversity.\r\n\r\nI haven\'t had the opportunity yet but I hope to have time to walk through the alleys of Ankara and exchange a few words with the city\'s elders. So I can try and see Turkey from their perspective. I am currently taking two courses that are entirely taught in Turkish so I don\'t think this day is too far out!\" ', 'img/story/humansofbilkent6.jpg', 'humansofbilkent boy esn uplift hill', 2745, '2020-06-06 20:19:57'),
(338, '\"Imagine being the only student from your country in Bilkent. You are excited at first because you have a chance to start over. You make some new friends that all happen to be other internationals, the majority being from engineering departments. Your first year goes by, and even though you miss your Japanese friends, life is good. \r\n\r\nThen you see your friends get busy in their own lives because academics in Bilkent is no joke and your parents move back to Japan, leaving you alone in this place. This is when you have the epiphany that you are stranded in a foreign land, for God knows how long, with a culture and language that is completely oblivious to you. You agree with the terms that life has put you on and try your best to socialize and travel in an attempt to find how you fit in in this new place. However, a couple of setbacks bring you back to square one and you are left lying on your bed watching Netflix, wondering what else can you do to adapt to your new surroundings. This is what life in Bilkent has been for me so far. \r\n\r\nFrom an extroverted person in Japan to an introvert in Bilkent, from a highly ambitious student to someone who has lost his passion in life, from partying with friends to drinking alone, I was constantly trying to find a balance between the two extremes of lives I was in. \r\n\r\nHonestly, as time passed by, I became tired of trying. Wouldn\'t you have? I stopped going to the classes, I guess I didn\'t have alot to look forward to. I started to regret my decision of moving to Turkey. Well, university life is no bed of roses. It\'s a brutal battle to maintain a balance between your social and academic lives, and a struggle to literally prevent tears from rolling down your cheeks. \r\n\r\nI\'m almost constantly struggling with the feeling that I\'m not putting my talents and time into good use. I\'ve faced many hardships during my time in Bilkent but I\'ve also met some amazing people who still make me want to stay here. Bilkent does not have what I want to study so I\'m leaving soon but over the course of two years, I\'ve made many memories that I would cherish for times to come even back in Japan.\" ', 'img/story/humansofbilkent7.jpg', 'humansofbilkent boy farewell sad hill', 2642, '2020-06-06 20:22:55'),
(339, '\"During my first four semesters in Bilkent, I was exploring opportunities by going on trips, attending club meetings and interacting with diverse people. I was extremely outgoing and academics was not my primary focus at that time.\r\n\r\nNeedless to say, I did make a plethora of friends and got executive positions in some clubs. However, it all came down at the expense of compromising some courses and I have been taking seven courses for the past two semesters.\r\n\r\nWhat do I regret about my time here? Well Honestly, I don’t regret anything. I like to think that the more pressure that I take the more I perform. I like to push my limits and I think that is how I grow most as a person.\r\n\r\nThere were times of self-doubt when I wondered whether or not I’m in the right program or am I doing the right thing. However, I kept assuring my self that life is not always going to be like this, once I push through the hard part, I’m going to enjoy myself. \r\n\r\nPulling off the Bilkent International Festival was one of the biggest highlights of my time in Bilkent. I was worried till the last moment since there were so many things happening at the same time, there was so much to coordinate, and the expectations were high, but it all came together at the end because of the immense hard work that I and my peers put in.\r\n\r\nIf I hadn’t joined all the clubs that I’m part of and not met people I now know, I would have the same limited scope of interest that I had before coming to the university. To be honest, Bilkent is not the easiest place to socialize but if I am honest, some people don’t put in enough effort; they never go on trips or talk to new people. It\'s about getting out of your comfort zone, and trust me I know all the anxiety that a person faces by being in such situations but we only grow and explore by being a little uncomfortable.\r\n\r\nOn an ending note, I would like to thank all the peers and professors who helped me through this journey in Bilkent. I will always remember you guys.\"', 'img/story/humansofbilkent8.jpg', 'humansofbilkent uplift farewell boy study', 2437, '2020-06-06 20:35:26'),
(340, '\"I was with someone that I loved and cared for. She was the best thing that happened to me and I was genuinely happy at that time. But all good things have an end, don’t they? \r\n\r\nMy family expected the same joyful person that they sent to Bilkent when I came back home, but the miseries I faced were palpable on my face and I had to resort to lies to avoid any further questioning. \r\n\r\nI was diagnosed with clinical depression but that is something I knew for a long time. Dealing with a breakup and academic stress simultaneously is extremely hard and causes you to develop psychological issues that you never wanted. \r\n\r\nTo be honest, Bilkent made me stronger and provided me with a platform to make close friends; however, I’m constantly feeling alone even when I’m with other people. \r\n\r\nLike everyone, of course, I want a better academic standing. However, what I wish for the most is to find that one constant thing in life that I would want to care about. That one special thing that would help me forget about my past, and support me to find a new dynamic to my current life.\" ', 'img/story/humansofbilkent9.jpg', 'humansofbilkent boy bilkent fountain sad', 2657, '2020-06-06 20:36:47'),
(341, '\"When I booked my ticket back home, I never expected it was going to be the last time I was in Bilkent as a student. Only if I knew, I would have gone to Mayfest with my friends, listened to music, sung a song and just enjoyed the moment while it lasted. \r\n\r\nI was part of numerous student clubs, actively engaging in events around the campus. Within a span of a few days, I went from this socially outgoing person to someone locked in her room. \r\n\r\nHonestly, when the online classes started, I was excited to get back in the routine and interact with my professors and peers, it felt like the only remnant of my time at Bilkent. When I’m not busy doing assignments, I talk to my friends or play games with them. I feel in such difficult times, staying connected with our friends can give you a glimmer of hope since all of us are in this together. \r\n\r\nUniversity life is more than just getting good grades. You need to do something for the community as well. I realized this when a professor lauded my efforts for helping out the less fortunate ones while working for the TDP club. It became such an important part of my time at Bilkent that it honestly feels like I am graduating both from Bilkent and TDP. I just wish I had the chance for proper goodbyes to the people that I made so many amazing memories with. \r\n\r\nTo all non-graduating students out there, get the maximum out of your time in Bilkent. Join student clubs, interact with different people and cherish your time spent here. Many students just want to get done with the university life, however, when it ends abruptly like this, you realize you never wanted such a sudden end to your otherwise amazing university life. \r\n\r\nAlso, to fellow seniors out there, the feeling of frustration is mutual. Instead of thinking, you couldn’t spend more time with your friends at Bilkent, think of all the good times you have had here. Think of all the memories you have made and how lucky you are to experience this in the first place. We don’t have any control over the current situation. Just remember Bilkent by days you truly lived it.\" ', 'img/story/humansofbilkent10.jpg', 'humansofbilkent girl farewell sad fountain', 2540, '2020-06-06 20:38:20'),
(342, '\"Dear class of 2020, \r\n\r\nGoodbyes are never easy, especially when they are unpredictable. Instead of mulling over this predicament, let\'s take a moment to appreciate what you have been through. \r\n\r\nWalking down memory lane, you came to Bilkent as confused teenagers, living the life as you have always been told. The past years helped you meet people you never imagined to become a part of your family, gain knowledge that you never thought you would grasp on and experience things you once thought were far-fetched. \r\n\r\nYou have worked hours studying, working on projects, assignments, extra-curricular activities, building your social lives while maintaining ties with your family and peers.\r\n\r\nNot only this but you crossed numerous obstacles that life threw at you, overcame what you once thought was unimaginable and paved the way to success. You have earned every bit of this. You came, You saw, You conquered! \r\n\r\nCherish the moments your journey in Bilkent has given you, connect with the people who made Bilkent memorable for you and don\'t let them go even after Bilkent. Let this be the splendid beginning of a new chapter instead of just being the end of one. We wish you the absolute best for the finals and the life that lies beyond them. \r\n\r\nTo those reading this who are not yet graduating, lets make this psuedo-graduation memorable for those who are. Send those you know from the 2020 batch the thoughts you have for them, or the memories you have made with them. Send them this post to let them know that official graduation or not, their batch will always be remembered. ', 'img/story/humansofbilkent11.jpg', 'humansofbilkent odeon misc farewell', 5353, '2020-06-06 20:39:46');

-- --------------------------------------------------------

--
-- Table structure for table `sublist`
--

CREATE TABLE `sublist` (
  `email` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `sublist`
--

INSERT INTO `sublist` (`email`) VALUES
('talalahmad1998@icloud.com');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `story`
--
ALTER TABLE `story`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `story` ADD FULLTEXT KEY `tags` (`tags`);

--
-- Indexes for table `sublist`
--
ALTER TABLE `sublist`
  ADD PRIMARY KEY (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `story`
--
ALTER TABLE `story`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=343;
